language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GIT_TOKEN
  keep_history: true
  on:
    branch: master
