name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build and Deploy
      uses: sterlingwes/gh-pages-deploy-action@v1.1
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        source-directory: dist
        build-command: npm install && npm run build
