name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: avinal/github-pages-deploy-action@v0.9
      with:
        GITHUB_TOKEN: ${{ secrets.gitToken }}
        LANGUAGE: node
        PAGES_BRANCH: gh-pages
        DOCS_FOLDER: dist
        MAKE_COMMAND: npm install && npm run build
